//alle lichten aan
	
if(My_State.state == ON && Light_Master.state == ON){
	sendCommand(Light_Green, ON)
	sendCommand(Light_Staande, ON)
	sendCommand(Light_Read, ON)
	if(Network_Desktop.state == ON){
		sendCommand(Light_Computer, ON)
	}
	else{
		sendCommand(Light_Computer, OFF)
	}
}
else{
	sendCommand(Light_Staande, OFF)
	sendCommand(Light_Read, OFF)
	sendCommand(Light_Green, OFF)
	sendCommand(Light_Computer, OFF)
}