//alle lichten aan
	
if(Rule_State.state == ON){	
	if(My_Status.state == 4 && Light_Master.state == ON){
		sendCommand(Light_Staande, ON)
		sendCommand(Light_Read, ON)
		if(Network_Desktop.state == ON){
			sendCommand(Light_Computer, ON)
		}
		else{
			sendCommand(Light_Computer, OFF)
		}
		sendCommand(Light_Green, ON)
	}
	else{
		sendCommand(Light_Green, OFF)
		sendCommand(Light_Staande, OFF)
		sendCommand(Light_Read, OFF)
		sendCommand(Light_Computer, OFF)
	}
}